### PR TITLE
Check if document is valid before adding or removing annotations

### LINKED ISSUE #194: [IOS] Calling addAnnotation can crash the whole app.
**Current:**
When I try to add an an annotation with `addAnnotation` before the pdfViewer is ready, pspdfkit crashes the app.

**Expected**
The promise returned by addAnnotation should faill with a useful error message

**Steps to reproduce**
1. Use rn component: 
```
const { path } = this.props;
<PSPDFKitView
            ref="pdfView"
            style={[styles.pdfView]}
            onAnnotationsChanged={this.handleAnnotationsChanged}
            {...platformProps[os]}
            document={path}
          />
```
2. call addAnnotation with any annotation after the document prop was set, but before it loaded the pdf. 
```
this.refs.pdfView.addAnnotation({
      v: 1,
      type: 'pspdfkit/note',
      bbox: [
        460.8377990722656,
        199.1999969482422,
        24,
        24
      ],
      id: '01D68YW75EABFDE6RQBCEW6YCJ',
      opacity: 1,
      pageIndex: 0,
      createdAt: '2019-03-18T18:51:35.086+01:00',
      updatedAt: '2019-03-18T18:51:38.317+01:00',
      name: '01D68YW75EABFDE6RQBCEW6YCJ',
      color: '#FFD83F',
      icon: 'comment',
      text: 'fghjfghjghj'
    })
```

version: 1.23.0

### PR DESCRIPTION
**Pull request by radazzouz**
# Details

Fixes #194

This fixes the issue described in https://github.com/PSPDFKit/react-native/issues/194#issuecomment-482050508. In that sample project annotations were added before the document was loaded. So they were added to an invalid document.

This PR also updates our Xcode projects (`RCTPSPDFKit.xcodeproj` and `Catalog.xcodeproj`) to Xcode 10.2 and fixes warnings.

# Acceptance Criteria

- [x] Check if document is valid before adding or removing annotations.
- [x] When approved, right before merging, rebase with master and increment the package version in `package.json`, `package-lock.json`, and `samples/Catalog/package.json` (see example commit:  https://github.com/PSPDFKit/react-native/pull/202/commits/1bf805feef2ac268743e4905d94d6d8c8f16ec59).
- [ ] Create a new release (and tag) with the new package version (see https://github.com/PSPDFKit/react-native/releases).

### CODE REVIEW

**Comment by radazzouz** [comment]
The actual fix is https://github.com/PSPDFKit/react-native/pull/209/commits/f6554fc3777d7a8a5df189c66a7c3c1fa7c4f201

File: ios/RCTPSPDFKit/RCTPSPDFKitView.m [hunk 1]
```diff
@@ -280,6 +299,11 @@ - (void)setFormFieldValue:(NSString *)value fullyQualifiedName:(NSString *)fully
   }
 
   PSPDFDocument *document = self.pdfController.document;
+  if (![document isValid]) {
```
Comment (steviki) [inline ios/RCTPSPDFKit/RCTPSPDFKitView.m]: We could use dot notation for all the `isValid` checks.

```suggestion
  if (!document.isValid) {
```
